run:
  deadline: 5m

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - goconst
    - gocyclo
    - gofmt
    - revive
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - wrapcheck
  disable:
    - gosimple
    - staticcheck
    - structcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/yorkie-team/yorkie
  gosec:
    excludes:
      - G107  # Potential HTTP request made with variable url

  wrapcheck:
    ignoreSigRegexps:
      - Err[a-zA-Z]+
issues:
  exclude-use-default: false
